"""
VibeVoca — Seed Data Script
TSL(TOEIC Service List) + NGSL 기반 단어 데이터를 Bulk Insert합니다.
"""
import os
import sys
import time
import psycopg2
from psycopg2.extras import execute_values

# backend/ 를 sys.path에 추가
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.config import get_settings

settings = get_settings()

BASIC_WORDS = [
    ("ability",     "능력, 재능",           "/əˈbɪl.ə.ti/",      "noun",      1),
    ("about",       "~에 대해, 약",         "/əˈbaʊt/",          "preposition",1),
    ("above",       "~위에",               "/əˈbʌv/",          "preposition",1),
    ("accept",      "받아들이다, 수락하다",   "/əkˈsept/",         "verb",      1),
    ("account",     "계좌; 설명하다",        "/əˈkaʊnt/",         "noun",      2),
    ("achieve",     "달성하다, 이루다",       "/əˈtʃiːv/",         "verb",      2),
    ("across",      "가로질러, 건너서",       "/əˈkrɒs/",          "preposition",1),
    ("action",      "행동, 조치",            "/ˈæk.ʃən/",         "noun",      1),
    ("add",         "추가하다, 더하다",       "/æd/",              "verb",      1),
    ("address",     "주소; 다루다",          "/əˈdres/",          "noun",      2),
    ("advice",      "조언, 충고",            "/ədˈvaɪs/",         "noun",      2),
    ("advise",      "조언하다",              "/ədˈvaɪz/",         "verb",      2),
    ("agree",       "동의하다",              "/əˈɡriː/",          "verb",      1),
    ("allow",       "허용하다, 허락하다",     "/əˈlaʊ/",           "verb",      2),
    ("already",     "이미, 벌써",            "/ɔːlˈred.i/",        "adverb",    1),
    ("also",        "또한, 역시",            "/ˈɔːl.səʊ/",         "adverb",    1),
    ("always",      "항상, 언제나",          "/ˈɔːl.weɪz/",        "adverb",    1),
    ("amount",      "양, 금액",              "/əˈmaʊnt/",         "noun",      2),
    ("another",     "또 다른, 다른",         "/əˈnʌð.ər/",         "adjective", 1),
    ("answer",      "대답, 답변",            "/ˈɑːn.sər/",         "noun",      1),
    ("appear",      "나타나다, 보이다",       "/əˈpɪər/",           "verb",      2),
    ("apply",       "지원하다; 적용하다",     "/əˈplaɪ/",           "verb",      2),
    ("area",        "지역, 영역",            "/ˈeə.ri.ə/",        "noun",      1),
    ("arrive",      "도착하다",              "/əˈraɪv/",          "verb",      1),
    ("ask",         "묻다, 요청하다",         "/ɑːsk/",            "verb",      1),
    ("attention",   "주의, 주목",            "/əˈten.ʃən/",       "noun",      2),
    ("available",   "이용 가능한",           "/əˈveɪ.lə.bəl/",     "adjective", 2),
    ("base",        "기초; 두다",            "/beɪs/",            "noun",      1),
    ("beautiful",   "아름다운",              "/ˈbjuː.tɪ.fəl/",     "adjective", 1),
    ("become",      "되다",                  "/bɪˈkʌm/",          "verb",      1),
    ("begin",       "시작하다",              "/bɪˈɡɪn/",          "verb",      1),
    ("believe",     "믿다",                  "/bɪˈliːv/",         "verb",      1),
    ("benefit",     "혜택, 이점",            "/ˈben.ɪ.fɪt/",       "noun",      2),
    ("between",     "~사이에",              "/bɪˈtwiːn/",        "preposition",1),
    ("big",         "큰",                    "/bɪɡ/",             "adjective", 1),
    ("book",        "책; 예약하다",          "/bʊk/",             "noun",      1),
    ("both",        "둘 다",                 "/bəʊθ/",            "adjective", 1),
    ("bring",       "가져오다",              "/brɪŋ/",            "verb",      1),
    ("build",       "세우다, 건조하다",       "/bɪld/",            "verb",      2),
    ("business",    "사업, 일",              "/ˈbɪz.nɪs/",        "noun",      1),
    ("call",        "부르다; 전화하다",       "/kɔːl/",            "verb",      1),
    ("careful",     "주의 깊은",             "/ˈkeə.fəl/",        "adjective", 2),
    ("carry",       "나르다, 휴대하다",       "/ˈkær.i/",          "verb",      2),
    ("cause",       "원인; 야기하다",        "/kɔːz/",            "noun",      2),
    ("center",      "중심",                  "/ˈsen.tər/",        "noun",      1),
    ("certain",     "확실한; 어떤",          "/ˈsɜː.tən/",        "adjective", 2),
    ("change",      "변동; 바꾸다",          "/tʃeɪndʒ/",         "noun",      1),
    ("child",       "어린이",                "/tʃaɪld/",          "noun",      1),
    ("choose",      "선택하다",              "/tʃuːz/",           "verb",      1),
    ("city",        "도시",                  "/ˈsɪt.i/",          "noun",      1),
    ("close",       "닫다; 가까운",          "/kləʊz/",           "verb",      1),
    ("come",        "오다",                  "/kʌm/",             "verb",      1),
    ("common",      "공통의, 일반적인",       "/ˈkɒm.ən/",         "adjective", 2),
    ("company",     "회사",                  "/ˈkʌm.pə.ni/",      "noun",      1),
    ("compare",     "비교하다",              "/kəmˈpeər/",        "verb",      2),
    ("consider",    "고려하다",              "/kənˈsɪd.ər/",      "verb",      2),
    ("continue",    "계속하다",              "/kənˈtɪn.juː/",     "verb",      2),
    ("control",     "제어; 조절하다",        "/kənˈtrəʊl/",       "noun",      2),
    ("cost",        "비용; 들다",            "/kɒst/",            "noun",      2),
    ("could",       "할 수 있었다",          "/kʊd/",             "verb",      1),
    ("country",     "나라, 국가",            "/ˈkʌn.tri/",        "noun",      1),
    ("course",      "강좌; 방향",            "/kɔːs/",            "noun",      1),
    ("create",      "창조하다, 만들다",       "/kriˈeɪt/",         "verb",      2),
    ("decide",      "결정하다",              "/dɪˈsaɪd/",         "verb",      2),
    ("degree",      "도, 학위",              "/dɪˈɡriː/",          "noun",      2),
    ("describe",    "묘사하다, 설명하다",     "/dɪˈskraɪb/",       "verb",      2),
    ("develop",     "발달시키다, 개발하다",   "/dɪˈvel.əp/",       "verb",      2),
    ("different",   "다른",                  "/ˈdɪf.ər.ənt/",     "adjective", 1),
    ("difficult",   "어려운",                "/ˈdɪf.ɪ.kəlt/",     "adjective", 1),
    ("do",          "하다",                  "/duː/",             "verb",      1),
    ("early",       "이른; 일찍",            "/ˈɜː.li/",          "adjective", 1),
    ("easy",        "쉬운",                  "/ˈiː.zi/",          "adjective", 1),
    ("economic",    "경제의",                "/ˌiː.kəˈnɒm.ɪk/",   "adjective", 2),
    ("education",   "교육",                  "/ˌed.jʊˈkeɪ.ʃən/",   "noun",      1),
    ("effect",      "효과, 결과",            "/ɪˈfekt/",          "noun",      2),
    ("effort",      "노력",                  "/ˈef.ət/",          "noun",      2),
    ("experience",  "경험",                  "/ɪkˈspɪə.ri.əns/",  "noun",      2),
    ("explain",     "설명하다",              "/ɪkˈspleɪn/",       "verb",      2),
    ("eye",         "눈",                    "/aɪ/",              "noun",      1),
    ("face",        "얼굴; 직면하다",        "/feɪs/",            "noun",      1),
    ("fact",        "사실",                  "/fækt/",            "noun",      1),
    ("fall",        "떨어지다; 가을",        "/fɔːl/",            "verb",      1),
    ("family",      "가족",                  "/ˈfæm.əl.i/",       "noun",      1),
    ("far",         "먼",                    "/fɑːr/",            "adjective", 1),
    ("feel",        "느끼다",                "/fiːl/",            "verb",      1),
    ("few",         "거의 없는; 소수의",      "/fjuː/",            "adjective", 1),
    ("field",       "들판; 분야",            "/fiːld/",           "noun",      2),
    ("find",        "찾다, 발견하다",        "/faɪnd/",           "verb",      1),
    ("first",       "첫 번째의",             "/fɜːst/",           "adjective", 1),
    ("follow",      "따르다",                "/ˈfɒl.əʊ/",         "verb",      1),
    ("for",         "~를 위해",              "/fɔːr/",            "preposition",1),
    ("force",       "힘; 강요하다",          "/fɔːs/",            "noun",      2),
    ("form",        "형태; 형성하다",        "/fɔːm/",            "noun",      2),
    ("free",        "자유로운; 공짜의",       "/friː/",            "adjective", 1),
    ("friend",      "친구",                  "/frend/",           "noun",      1),
    ("from",        "~로부터",               "/frɒm/",            "preposition",1),
    ("full",        "가득 찬",               "/fʊl/",             "adjective", 1),
    ("general",     "일반적인; 장군",        "/ˈdʒen.ər.əl/",     "adjective", 2),
    ("get",         "받다, 얻다",            "/ɡet/",             "verb",      1),
    ("give",        "주다",                  "/ɡɪv/",             "verb",      1),
    ("go",          "가다",                  "/ɡəʊ/",             "verb",      1),
    ("good",        "좋은",                  "/ɡʊd/",             "adjective", 1),
    ("great",       "위대한, 큰",            "/ɡreɪt/",           "adjective", 1),
    ("ground",      "땅; 근거",              "/ɡraʊnd/",          "noun",      2),
    ("group",       "그룹, 집단",            "/ɡruːp/",           "noun",      1),
    ("grow",        "성장하다, 재배하다",     "/ɡrəʊ/",            "verb",      2),
    ("happen",      "어나다, 발생하다",       "/ˈhæp.ən/",         "verb",      1),
    ("have",        "가지다",                "/hæv/",             "verb",      1),
    ("head",        "머리; 이끌다",          "/hed/",             "noun",      1),
    ("hear",        "듣다",                  "/hɪər/",            "verb",      1),
    ("help",        "돕다; 도움",            "/help/",            "verb",      1),
    ("here",        "여기",                  "/hɪər/",            "adverb",    1),
    ("high",        "높은",                  "/haɪ/",             "adjective", 1),
    ("history",     "역사",                  "/ˈhɪs.tər.i/",       "noun",      1),
    ("hold",        "잡다; 개최하다",        "/həʊld/",           "verb",      2),
    ("hope",        "희망; 희망하다",        "/həʊp/",            "noun",      1),
    ("hour",        "시간",                  "/aʊər/",            "noun",      1),
    ("how",         "어떻게, 얼마나",        "/haʊ/",             "adverb",    1),
    ("however",     "그러나",                "/haʊˈev.ər/",       "adverb",    2),
    ("human",       "인간의; 인간",          "/ˈhjuː.mən/",       "adjective", 2),
    ("idea",        "아이디어, 생각",        "/aɪˈdɪə/",          "noun",      1),
    ("if",          "만약 ~라면",            "/ɪf/",              "conjunction",1),
    ("imagine",     "상상하다",              "/ɪˈmædʒ.ɪn/",       "verb",      2),
    ("important",   "중요한",                "/ɪmˈpɔː.tənt/",     "adjective", 1),
    ("include",     "포함하다",              "/ɪnˈkluːd/",        "verb",      2),
    ("increase",    "증가; 증가하다",        "/ɪnˈkriːs/",        "noun",      2),
    ("industry",    "산업; 공업",            "/ˈɪn.də.stri/",     "noun",      2),
    ("information", "정보",                  "/ˌɪn.fəˈmeɪ.ʃən/",   "noun",      1),
    ("interest",    "관심; 이자",            "/ˈɪn.trəst/",       "noun",      2),
    ("into",        "~ 안으로",              "/ˈɪn.tuː/",         "preposition",1),
    ("issue",       "논쟁점; 발행하다",       "/ˈɪʃ.uː/",          "noun",      2),
    ("just",        "방금; 단지; 공정한",     "/dʒʌst/",           "adverb",    1),
    ("keep",        "유지하다, 계속하다",     "/kiːp/",            "verb",      1),
    ("know",        "알다",                  "/nəʊ/",             "verb",      1),
    ("knowledge",   "지식",                  "/ˈnɒl.ɪdʒ/",        "noun",      2),
    ("law",         "법, 법률",              "/lɔː/",             "noun",      1),
    ("lead",        "이끌다; 납",            "/liːd/",            "verb",      2),
    ("leave",       "떠나다; 휴가",          "/liːv/",            "verb",      1),
    ("less",        "더 적은; 덜",           "/les/",             "adjective", 2),
    ("let",         "허락하다; ~하게 하다",   "/let/",             "verb",      1),
    ("like",        "좋아하다; ~와 같은",     "/laɪk/",            "verb",      1),
    ("likely",      "~할 것 같은",           "/ˈlaɪ.kli/",        "adjective", 2),
    ("line",        "선, 줄",                "/laɪn/",            "noun",      1),
    ("listen",      "듣다, 경청하다",        "/ˈlɪs.ən/",         "verb",      1),
    ("little",      "작은; 거의 없는",        "/ˈlɪt.əl/",         "adjective", 1),
    ("live",        "살다; 생방송의",        "/lɪv/",             "verb",      1),
    ("look",        "보다; ~처럼 보이다",     "/lʊk/",             "verb",      1),
    ("lose",        "잃다, 지다",            "/luːz/",            "verb",      2),
    ("low",         "낮은",                  "/ləʊ/",             "adjective", 1),
    ("make",        "만들다",                "/meɪk/",            "verb",      1),
    ("manage",      "경영하다, 관리하다",     "/ˈmæn.ɪdʒ/",        "verb",      2),
    ("many",        "많은",                  "/ˈmen.i/",          "adjective", 1),
    ("market",      "시장",                  "/ˈmɑː.kɪt/",        "noun",      2),
    ("matter",      "문제; 중요하다",        "/ˈmæt.ər/",         "noun",      2),
    ("maybe",       "아마도",                "/ˈmeɪ.bi/",         "adverb",    1),
    ("mean",        "의미하다; 비열한",       "/miːn/",            "verb",      2),
    ("measure",     "측정하다; 측정",        "/ˈmež.ər/",         "verb",      2),
    ("meeting",     "회의",                  "/ˈmiː.tɪŋ/",        "noun",      1),
    ("member",      "구성원",                "/ˈmem.ər/",         "noun",      1),
    ("might",       "~일지도 모른다; 힘",     "/maɪt/",            "verb",      2),
    ("mind",        "마음; 꺼리다",          "/maɪnd/",           "noun",      2),
    ("money",       "돈",                    "/ˈmʌn.i/",          "noun",      1),
    ("month",       "달, 월",                "/mʌnθ/",            "noun",      1),
    ("more",        "더 많은; 더",           "/mɔːr/",            "adjective", 1),
    ("most",        "가장 많은; 대부분",     "/məʊst/",           "adjective", 1),
    ("move",        "움직이다; 이사하다",     "/muːv/",            "verb",      1),
    ("much",        "많은; 훨씬",            "/mʌtʃ/",            "adjective", 1),
    ("must",        "~해야 한다",            "/mʌst/",            "verb",      1),
    ("name",        "이름; 명명하다",        "/neɪm/",            "noun",      1),
    ("natural",     "자연의, 타고난",        "/ˈnætʃ.ər.əl/",      "adjective", 2),
    ("near",        "가까운; 근처에",        "/nɪər/",            "adjective", 1),
    ("need",        "필요하다; 욕구",        "/niːd/",            "verb",      1),
    ("never",       "결코 ~않다",            "/ˈnev.ər/",         "adverb",    1),
    ("new",         "새로운",                "/njuː/",            "adjective", 1),
    ("next",        "다음의; 옆에",          "/nekst/",           "adjective", 1),
    ("night",       "밤",                    "/naɪt/",            "noun",      1),
    ("no",          "아니오; 없는",          "/nəʊ/",             "adverb",    1),
    ("not",         "~않다",                 "/nɒt/",             "adverb",    1),
    ("now",         "지금, 현재",            "/|naʊ/",             "adverb",    1),
    ("number",      "숫자, 번호",            "/ˈnʌm.ər/",         "noun",      1),
    ("off",         "떨어져서, 꺼져",        "/ɒf/",              "adverb",    1),
    ("offer",       "제공하다; 제안",        "/ˈɒf.ər/",          "verb",      2),
    ("often",       "종종, 자주",            "/ˈɒf.ən/",          "adverb",    1),
    ("old",         "나이 든, 오래된",        "/əʊld/",            "adjective", 1),
    ("on",          "~ 위에; 켜진",          "/ɒn/",              "preposition",1),
    ("once",        "한 번; 일단 ~하면",      "/wʌns/",            "adverb",    2),
    ("one",         "하나, 하나인",          "/wʌn/",             "number",    1),
    ("only",        "오직, 단지",            "/ˈəʊn.li/",         "adverb",    1),
    ("open",        "열다; 열린",            "/ˈəʊ.pən/",         "verb",      1),
    ("opinion",     "의견",                  "/əˈpɪn.jən/",       "noun",      2),
    ("order",       "주문; 순서; 명령",       "/ˈɔː.dər/",         "noun",      2),
    ("other",       "다른",                  "/ˈʌð.ər/",          "adjective", 1),
    ("out",         "밖으로; 떨어진",        "/aʊt/",             "adverb",    1),
    ("over",        "~ 너머; 끝난",          "/ˈəʊ.vər/",         "preposition",1),
    ("own",         "자신의; 소유하다",       "/əʊn/",             "verb",      2),
    ("page",        "페이지, 쪽",            "/peɪdʒ/",           "noun",      1),
    ("part",        "부분; 역할",            "/pɑːt/",            "noun",      1),
    ("party",       "파티; 정당",            "/ˈpɑː.ti/",         "noun",      1),
    ("place",       "장소; 두다",            "/pleɪs/",           "noun",      1),
    ("plan",        "계획; 계획하다",        "/plæn/",            "noun",      1),
    ("play",        "놀다; 공연; 경기하다",    "/pleɪ/",            "verb",      1),
    ("point",       "점; 의미; 가리키다",     "/pɔɪnt/",           "noun",      2),
    ("possible",    "가능한",                "/ˈpɒs.ə.bəl/",      "adjective", 1),
    ("power",       "힘, 권력",              "/paʊər/",           "noun",      2),
    ("present",     "현재의; 제시하다; 선물",   "/ˈprez.ənt/",       "adjective", 2),
    ("president",   "대통령, 회장",          "/ˈprez.ɪ.dənt/",    "noun",      2),
    ("price",       "가격",                  "/praɪs/",           "noun",      1),
    ("private",     "개인적인, 사설의",       "/ˈpraɪ.vət/",       "adjective", 2),
    ("problem",     "문제",                  "/ˈprɒb.ləm/",       "noun",      1),
    ("process",     "과정; 처리하다",        "/ˈprəʊ.ses/",       "noun",      2),
    ("produce",     "생산하다; 농산물",       "/prəˈdʒuːs/",       "verb",      2),
    ("product",     "제품, 제품군",          "/ˈprɒd.ʌkt/",       "noun",      2),
    ("provide",     "제공하다, 공급하다",     "/prəˈvaɪd/",        "verb",      2),
    ("public",      "공공의; 대중",          "/ˈpʌb.lɪk/",        "adjective", 1),
    ("quality",     "질, 품질",              "/ˈkwɒl.ə.ti/",      "noun",      2),
    ("recent",      "최근의",                "/ˈriː.sənt/",       "adjective", 2),
    ("total",       "전체의; 합계",          "/ˈtəʊ.təl/",        "adjective", 2),
    ("understand",  "이해하다",              "/ˌʌn.dəˈstænd/",    "verb",      1),
    ("useful",      "유용한",                "/ˈjuːs.fəl/",       "adjective", 2),
    ("various",     "다양한",                "/ˈveə.ri.əs/",      "adjective", 2),
    ("value",       "가치; 중요성",          "/ˈvæl.juː/",        "noun",      2),
    ("world",       "세계, 세상",            "/wɜːld/",           "noun",      1),
]

WORDS_800 = [
    # TSL 800점 수준 (발음 기호 포함)
    ("abandon",      "포기하다, 버리다",      "/əˈbæn.dən/",       "verb",      3),
    ("abstract",     "추상적인, 개요",        "/ˈæb.strækt/",      "adjective", 4),
    ("abundant",     "풍부한",               "/əˈbʌn.dənt/",      "adjective", 4),
    ("accelerate",   "가속하다",             "/əkˈsel.ə.reɪt/",    "verb",      4),
    ("accessible",   "접근 가능한",           "/əkˈses.ə.bəl/",    "adjective", 3),
    ("accommodate",  "수용하다, 숙박시키다",   "/əˈkɒm.ə.deɪt/",    "verb",      3),
    ("accompany",    "동반하다",             "/əˈkʌm.pə.ni/",     "verb",      3),
    ("accomplish",   "성취하다",             "/əˈkʌm.plɪʃ/",      "verb",      3),
    ("accumulate",   "축적하다",             "/əˈkjuː.mjə.leɪt/",  "verb",      4),
    ("accurate",     "정확한",               "/ˈæk.jə.rət/",      "adjective", 3),
    ("acknowledge",  "인정하다, 알리다",      "/əkˈnɒl.ɪdʒ/",      "verb",      3),
    ("acquire",      "습득하다, 획득하다",     "/əˈkwaɪər/",        "verb",      3),
    ("adequate",     "적절한, 충분한",        "/ˈæd.ə.kwət/",      "adjective", 3),
    ("adjacent",     "인접한",               "/əˈdʒeɪ.sənt/",     "adjective", 4),
    ("adjust",       "조절하다, 적응하다",     "/əˈdʒʌst/",         "verb",      3),
    ("administration","행정, 관리",           "/ədˌmɪn.ɪˈstreɪ.ʃən/","noun",      3),
    ("advocate",     "지지하다, 옹호하다",     "/ˈæd.və.keɪt/",     "verb",      4),
    ("aggregate",    "합계의, 집합",          "/ˈæɡ.rɪ.ɡət/",      "adjective", 4),
    ("alleviate",    "완화하다",             "/əˈliː.vi.eɪt/",    "verb",      4),
    ("allocate",     "할당하다, 배분하다",     "/ˈæl.ə.keɪt/",      "verb",      4),
    ("alter",        "변경하다",             "/ˈɒl.tər/",         "verb",      3),
    ("alternative",  "대안; 대체의",          "/ɒlˈtɜː.nə.tɪv/",   "noun",      3),
    ("ambiguous",    "모호한",               "/æmˈbɪɡ.ju.əs/",    "adjective", 4),
    ("amend",        "개정하다, 수정하다",     "/əˈmend/",          "verb",      4),
    ("analogy",      "비유, 유사점",          "/əˈnæl.ə.dʒi/",     "noun",      4),
    ("analyze",      "분석하다",             "/ˈæn.əl.aɪz/",      "verb",      3),
    ("anticipate",   "예상하다, 기대하다",     "/ænˈtɪs.ɪ.peɪt/",   "verb",      3),
    ("apparent",     "명백한, 외견상의",      "/əˈpær.ənt/",       "adjective", 3),
    ("appendix",     "부록",                 "/əˈpen.dɪks/",      "noun",      4),
    ("appreciate",   "감사하다; 감상하다",     "/əˈpriː.ʃi.eɪt/",   "verb",      3),
    ("approach",     "접근하다; 방법",        "/əˈprəʊtʃ/",        "verb",      3),
    ("appropriate",  "적절한",               "/əˈprəʊ.pri.ət/",   "adjective", 3),
    ("approximate",  "대략의",               "/əˈprɒk.sɪ.mət/",   "adjective", 4),
    ("arbitrary",    "임의적인, 독단적인",     "/ˈɑː.bɪ.trər.i/",   "adjective", 4),
    ("aspect",       "측면, 양상",            "/ˈæs.pekt/",        "noun",      3),
    ("assemble",     "조립하다, 모으다",      "/əˈsem.bəl/",       "verb",      3),
    ("assess",       "평가하다",             "/əˈses/",           "verb",      3),
    ("assign",       "할당하다, 부여하다",     "/əˈsaɪn/",          "verb",      3),
    ("assist",       "돕다",                 "/əˈsɪst/",          "verb",      3),
    ("assume",       "가정하다; 떠맡다",      "/əˈsjuːm/",         "verb",      3),
    ("assure",       "보장하다, 확언하다",     "/əˈʃɔːr/",          "verb",      3),
    ("attach",       "첨부하다, 붙이다",      "/əˈtætʃ/",          "verb",      3),
    ("attain",       "달성하다",             "/əˈteɪn/",          "verb",      4),
    ("attribute",    "~의 탓으로 돌리다",     "/əˈtrɪb.juːt/",     "verb",      4),
    ("automate",     "자동화하다",            "/ˈɔː.tə.meɪt/",     "verb",      4),
    ("barrier",      "장벽, 장애물",          "/ˈbær.i.ər/",       "noun",      3),
    ("benefit",      "이익, 혜택",            "/ˈben.ɪ.fɪt/",      "noun",      3),
    ("bias",         "편견, 성향",            "/ˈbaɪ.əs/",         "noun",      4),
    ("bond",         "유대, 채권",            "/bɒnd/",            "noun",      4),
    ("brief",        "짧은, 잠시동안의",      "/briːf/",           "adjective", 3),
    ("bulk",         "대량, 부피",            "/bʌlk/",            "noun",      4),
    ("capable",      "능력 있는",            "/ˈkeɪ.pə.bəl/",     "adjective", 3),
    ("capacity",     "능력, 용량",            "/kəˈpæs.ə.ti/",     "noun",      3),
    ("category",     "범주, 카테고리",        "/ˈkæt.ə.ɡri/",      "noun",      3),
    ("cease",        "중단하다",             "/siːs/",            "verb",      4),
    ("channel",      "경로, 채널",            "/ˈtʃæn.əl/",        "noun",      3),
    ("circumstance", "상황, 환경",            "/ˈsɜː.kəm.stəns/",  "noun",      3),
    ("cite",         "인용하다",             "/saɪt/",            "verb",      4),
    ("civil",        "시민의, 민간의",        "/ˈsɪv.əl/",         "adjective", 4),
    ("clarify",      "명확하게 하다",         "/ˈklær.ɪ.faɪ/",     "verb",      3),
    ("classic",      "전형적인, 고전의",      "/ˈklæs.ɪk/",        "adjective", 4),
    ("clause",       "조항, 절",             "/klɔːz/",           "noun",      4),
    ("code",         "규범, 코드",            "/kəʊd/",            "noun",      3),
    ("coherent",     "일관성 있는",           "/kəʊˈhɪə.rənt/",    "adjective", 4),
    ("coincide",     "동시에 일어나다",       "/ˌkəʊ.ɪnˈsaɪd/",    "verb",      4),
    ("collapse",     "붕괴하다",             "/kəˈlæps/",         "verb",      4),
    ("colleague",    "동료",                 "/ˈkɒl.iːɡ/",        "noun",      3),
    ("commence",     "시작하다",             "/kəˈmens/",         "verb",      4),
    ("comment",      "비평, 의견",            "/ˈkɒm.ent/",        "noun",      3),
    ("commission",   "수수료, 위원회",        "/kəˈmɪʃ.ən/",       "noun",      3),
    ("commit",       "전념하다, 약속하다",     "/kəˈmɪt/",          "verb",      3),
    ("commodity",    "상품, 물자",            "/kəˈmɒd.ə.ti/",     "noun",      4),
    ("communicate",  "의사소통하다",          "/kəˈmjuː.nɪ.keɪt/", "verb",      3),
    ("community",    "공동체, 사회",          "/kəˈmjuː.nə.ti/",    "noun",      3),
    ("compatible",   "호환되는",             "/kəmˈpæt.ə.bəl/",   "adjective", 3),
    ("compensate",   "보상하다",             "/ˈkɒm.pən.seɪt/",   "verb",      3),
    ("compile",      "엮다, 편집하다",        "/kəmˈpaɪl/",        "verb",      4),
    ("complement",   "보완하다",             "/ˈkɒm.plɪ.ment/",   "verb",      4),
    ("complex",      "복잡한",               "/ˈkɒm.pleks/",      "adjective", 3),
    ("component",    "요소, 부품",            "/kəmˈpəʊ.nənt/",    "noun",      3),
    ("compound",     "혼합물",               "/ˈkɒm.paʊnd/",      "noun",      4),
    ("comprehensive","종합적인",             "/ˌkɒm.prɪˈhen.sɪv/","adjective", 3),
    ("comprise",     "~으로 구성되다",        "/kəmˈpraɪz/",       "verb",      4),
    ("compute",      "계산하다",             "/kəmˈpjuːt/",       "verb",      4),
    ("conceive",     "상상하다, 임신하다",     "/kənˈsiːv/",        "verb",      4),
    ("concentrate",  "집중하다",             "/ˈkɒn.sən.treɪt/",  "verb",      3),
    ("concept",      "개념",                 "/ˈkɒn.sept/",       "noun",      3),
    ("conclude",     "결론짓다",             "/kənˈkluːd/",       "verb",      3),
    ("concurrent",   "동시에 일어나는",       "/kənˈkʌr.ənt/",     "adjective", 4),
    ("conduct",      "수행하다; 행동",        "/kənˈdʌkt/",        "verb",      3),
    ("confer",       "협의하다, 수여하다",     "/kənˈfɜːr/",         "verb",      4),
    ("confine",      "제한하다, 가두다",      "/kənˈfaɪn/",        "verb",      4),
    ("confirm",      "확인하다",             "/kənˈfɜːm/",        "verb",      3),
    ("conflict",     "충돌, 갈등",            "/ˈkɒn.flɪkt/",      "noun",      3),
    ("conform",      "순응하다, 일치하다",     "/kənˈfɔːm/",        "verb",      4),
    ("consent",      "동의하다",             "/kənˈsent/",        "verb",      4),
    ("consequence",  "결과, 중요성",          "/ˈkɒn.sɪ.kwəns/",   "noun",      3),
    ("considerable", "상당한",               "/kənˈsɪd.ər.ə.bəl/", "adjective", 3),
    ("consist",      "~로 구성되다",          "/kənˈsɪst/",        "verb",      3),
    ("constant",     "지속적인",             "/ˈkɒn.stənt/",      "adjective", 3),
    ("constitute",   "구성하다",             "/ˈkɒn.stɪ.tʃuːt/",  "verb",      4),
    ("constrain",    "제한하다",             "/kənˈstreɪn/",      "verb",      4),
    ("construct",    "건설하다",             "/kənˈstrʌkt/",      "verb",      3),
    ("consult",      "상담하다",             "/kənˈsʌlt/",        "verb",      3),
    ("consume",      "소비하다",             "/kənˈsjuːm/",       "verb",      3),
    ("contact",      "접촉하다",             "/ˈkɒn.tækt/",       "verb",      3),
    ("contemporary", "동시대의, 현대의",      "/kənˈtem.pə.rər.i/", "adjective", 4),
    ("context",      "맥락, 문맥",            "/ˈkɒn.tekst/",      "noun",      3),
    ("contract",     "계약; 수축하다",        "/ˈkɒn.trækt/",      "noun",      3),
    ("contradict",   "모순되다, 부정하다",     "/ˌkɒn.trəˈdɪkt/",   "verb",      4),
    ("contrary",     "반대의",               "/ˈkɒn.trə.ri/",     "adjective", 3),
    ("contrast",     "대조",                 "/ˈkɒn.trɑːst/",     "noun",      3),
    ("contribute",   "기여하다",             "/kənˈtrɪb.juːt/",   "verb",      3),
    ("controversy",  "논란",                 "/ˈkɒn.trə.vɜː.si/", "noun",      4),
    ("convene",      "모이다, 소집하다",      "/kənˈviːn/",        "verb",      4),
    ("converse",     "대화하다; 반대의",      "/kənˈvɜːs/",         "verb",      4),
    ("convert",      "전환하다",             "/kənˈvɜːt/",         "verb",      3),
    ("convince",     "확신시키다",           "/kənˈvɪns/",        "verb",      3),
    ("coordinate",   "조정하다",             "/kəʊˈɔː.dɪ.neɪt/",   "verb",      4),
    ("core",         "핵심",                 "/kɔːr/",            "noun",      3),
    ("corporate",    "법인의, 기업의",        "/ˈkɔː.pər.ət/",     "adjective", 3),
    ("correspond",   "일치하다, 서신왕래하다",  "/ˌkɒr.ɪˈspɒnd/",    "verb",      4),
    ("couple",       "한 쌍",                "/ˈkʌn.pəl/",        "noun",      3),
    ("create",       "창조하다",             "/kriˈeɪt/",         "verb",      3),
    ("credit",       "신용, 학점",            "/ˈkred.ɪt/",        "noun",      3),
    ("criteria",     "기준",                 "/kraɪˈtɪə.ri.ə/",    "noun",      4),
    ("crucial",      "중요한",               "/ˈkruː.ʃəl/",       "adjective", 3),
    ("culture",      "문화",                 "/ˈkʌl.tʃər/",       "noun",      3),
    ("currency",     "통화",                 "/ˈkʌr.ən.si/",      "noun",      3),
    ("cycle",        "순환",                 "/ˈsaɪ.kəl/",        "noun",      3),
    ("data",         "데이터",               "/ˈdeɪ.tə/",         "noun",      3),
    ("debate",       "토론",                 "/dɪˈbeɪt/",         "noun",      3),
    ("decade",       "10년",                 "/ˈdek.eɪd/",        "noun",      3),
    ("decline",      "거절하다, 하락하다",     "/dɪˈklaɪn/",        "verb",      3),
    ("deduce",       "추론하다",             "/dɪˈdʒuːs/",        "verb",      4),
    ("define",       "정의하다",             "/dɪˈfaɪn/",         "verb",      3),
    ("definite",     "명확한",               "/ˈdef.ɪ.nət/",      "adjective", 3),
    ("demonstrate",  "입증하다, 시연하다",     "/ˈdem.ən.streɪt/",  "verb",      3),
    ("denote",       "나타내다",             "/dɪˈnəʊt/",         "verb",      4),
    ("deny",         "부인하다",             "/dɪˈnaɪ/",          "verb",      3),
    ("depress",      "우울하게 하다, 침체시키다","/dɪˈpres/",          "verb",      4),
    ("derive",       "이끌어내다, 유래하다",   "/dɪˈraɪv/",         "verb",      4),
    ("design",       "디자인하다",           "/dɪˈzaɪn/",         "verb",      3),
    ("despite",      "~에도 불구하고",        "/dɪˈspaɪt/",        "preposition",3),
    ("detect",       "감지하다",             "/dɪˈtekt/",         "verb",      3),
    ("deviate",      "벗어나다",             "/ˈdiː.vi.eɪt/",     "verb",      4),
    ("device",       "장치",                 "/dɪˈvaɪs/",         "noun",      3),
    ("devote",       "헌신하다",             "/dɪˈvəʊt/",         "verb",      3),
    ("differentiate","구별하다",             "/ˌdɪf.əˈren.ʃi.eɪt/","verb",      4),
    ("dimension",    "치수, 차원",            "/ˌdaɪˈmen.ʃən/",    "noun",      4),
    ("diminish",     "줄어들다",             "/dɪˈmɪn.ɪʃ/",       "verb",      4),
    ("discrere",     "별개의",               "/dɪˈskriːt/",       "adjective", 4),
    ("discriminate", "차별하다, 식별하다",     "/dɪˈskrɪm.ɪ.neɪt/", "verb",      4),
    ("displace",     "대체하다, 쫓아내다",     "/dɪˈspleɪs/",       "verb",      4),
    ("display",      "전시하다",             "/dɪˈspleɪ/",        "verb",      3),
    ("dispose",      "처분하다",             "/dɪˈspəʊz/",        "verb",      3),
    ("distinct",     "별개의, 뚜렷한",        "/dɪˈstɪŋkt/",       "adjective", 3),
    ("distort",      "왜곡하다",             "/dɪˈstɔːt/",        "verb",      4),
    ("distribute",   "배포하다",             "/dɪˈstrɪb.juːt/",   "verb",      3),
    ("diverse",      "다양한",               "/daɪˈvɜːs/",        "adjective", 3),
    ("document",     "서류, 문서",            "/ˈdɒk.jə.mənt/",    "noun",      3),
    ("domain",       "영역, 도메인",          "/dəʊˈmeɪn/",        "noun",      4),
    ("domestic",     "국내의, 가정의",        "/dəˈmes.tɪk/",      "adjective", 3),
    ("dominate",     "지배하다",             "/ˈdɒm.ɪ.neɪt/",     "verb",      4),
    ("draft",        "초안",                 "/drɑːft/",          "noun",      3),
    ("drama",        "드라마",               "/ˈdrɑː.mə/",        "noun",      3),
    ("duration",     "지속 시간",            "/djuəˈreɪ.ʃən/",    "noun",      4),
    ("dynamic",      "역동적인",             "/daɪˈnæm.ɪk/",      "adjective", 4),
    ("economy",      "경제",                 "/iˈkɒn.ə.mi/",      "noun",      3),
    ("edit",         "편집하다",             "/ˈed.ɪt/",          "verb",      3),
    ("element",      "요소",                 "/ˈel.ɪ.mənt/",      "noun",      3),
    ("eliminate",    "제거하다",             "/iˈlɪm.ɪ.neɪt/",    "verb",      3),
    ("emerge",       "나타나다",             "/iˈmɜːdʒ/",         "verb",      3),
    ("emphasis",     "강조",                 "/ˈem.fə.sɪs/",      "noun",      3),
    ("empirical",    "경험적인",             "/ɪmˈpɪr.ɪ.kəl/",    "adjective", 4),
    ("enable",       "가능하게 하다",         "/ɪˈneɪ.bəl/",       "verb",      3),
    ("encounter",    "직면하다, 마주치다",     "/ɪnˈkaʊn.tər/",     "verb",      3),
    ("energy",       "에너지",               "/ˈen.ə.dʒi/",       "noun",      3),
    ("enforce",      "집행하다, 강요하다",     "/ɪnˈfɔːs/",         "verb",      3),
    ("enhance",      "강화하다, 향상시키다",   "/ɪnˈhɑːns/",        "verb",      3),
    ("enormous",     "대한, 거대한",          "/ɪˈnɔː.məs/",       "adjective", 3),
    ("ensure",       "보장하다",             "/ɪnˈʃɔːr/",          "verb",      3),
    ("entity",       "실체, 독립체",          "/ˈen.tə.ti/",       "noun",      4),
    ("environment",  "환경",                 "/ɪnˈvaɪ.rən.mənt/", "noun",      3),
    ("equate",       "동일시하다",           "/ɪˈkweɪt/",         "verb",      4),
    ("equip",        "갖추다, 장착하다",      "/ɪˈkwɪp/",          "verb",      3),
    ("equivalent",   "동등한",               "/ɪˈkwɪv.əl.ənt/",   "adjective", 4),
    ("erode",        "침식하다",             "/ɪˈrəʊd/",          "verb",      4),
    ("erroneous",    "잘못된",               "/ɪˈrəʊ.ni.əs/",     "adjective", 4),
    ("essential",    "필수적인",             "/ɪˈsen.ʃəl/",       "adjective", 3),
    ("establish",    "설립하다, 확립하다",     "/ɪˈstæb.lɪʃ/",      "verb",      3),
    ("estate",       "재산, 부동산",          "/ɪˈsteɪt/",         "noun",      3),
    ("estimate",     "견적; 추정하다",        "/ˈes.tɪ.meɪt/",     "verb",      3),
    ("ethic",        "윤리",                 "/ˈeθ.ɪk/",          "noun",      4),
    ("ethnic",       "민족의",               "/ˈeθ.nɪk/",         "adjective", 4),
    ("evaluate",     "평가하다",             "/ɪˈvæl.ju.eɪt/",    "verb",      3),
    ("eventual",     "최종적인",             "/ɪˈven.tʃu.əl/",    "adjective", 3),
    ("evident",      "분명한",               "/ˈev.ɪ.dənt/",      "adjective", 3),
    ("evolve",       "진화하다, 발전하다",     "/ɪˈvɒlv/",          "verb",      4),
    ("exceed",       "초과하다",             "/ɪkˈsiːd/",         "verb",      3),
    ("exclude",      "제외하다",             "/ɪkˈskluːd/",       "verb",      3),
    ("exhibit",      "전시하다; 전시물",      "/ɪɡˈzɪb.ɪt/",       "verb",      3),
    ("expand",       "확장하다",             "/ɪkˈspænd/",        "verb",      3),
    ("expert",       "전문가",               "/ˈek.spɜːt/",       "noun",      3),
    ("explicit",     "명백한, 노골적인",      "/ɪkˈsplɪs.ɪt/",     "adjective", 4),
    ("exploit",      "이용하다, 착취하다",     "/ɪkˈsplɔɪt/",       "verb",      4),
    ("export",       "수출하다",             "/ɪkˈspɔːt/",        "verb",      3),
    ("expose",       "노출시키다",           "/ɪkˈspəʊz/",        "verb",      3),
    ("external",     "외부의",               "/ɪkˈstɜː.nəl/",     "adjective", 3),
    ("extract",      "추출하다",             "/ɪkˈstrækt/",       "verb",      4),
    ("facilitate",   "용이하게 하다",         "/fəˈsɪl.ɪ.teɪt/",   "verb",      4),
    ("factor",       "요소",                 "/ˈfæk.tər/",        "noun",      3),
    ("feature",      "특징",                 "/ˈfiː.tʃər/",       "noun",      3),
    ("federal",      "연방의",               "/ˈfed.ər.əl/",      "adjective", 4),
    ("fee",          "수수료",               "/fiː/",             "noun",      3),
    ("file",         "파일, 서류철",          "/faɪl/",            "noun",      3),
    ("final",        "최종의",               "/ˈfaɪ.nəl/",        "adjective", 3),
    ("finance",      "금융, 재정",            "/ˈfaɪ.næns/",       "noun",      3),
    ("finite",       "유한한",               "/ˈfaɪ.naɪt/",       "adjective", 4),
    ("flexible",     "유연한",               "/ˈflek.sə.bəl/",    "adjective", 3),
    ("fluctuate",    "변동하다",             "/ˈflʌk.tʃu.eɪt/",   "verb",      4),
    ("focus",        "집중",                 "/ˈfəʊ.kəs/",        "noun",      3),
    ("format",       "형식, 포맷",            "/ˈfɔː.mæt/",        "noun",      3),
    ("formula",      "공식",                 "/ˈfɔː.mjə.lə/",     "noun",      3),
    ("forthcoming",  "다가오는",             "/ˌfɔːθˈkʌm.ɪŋ/",    "adjective", 4),
    ("foundation",   "기초, 토대",            "/faʊnˈdeɪ.ʃən/",    "noun",      3),
    ("framework",    "틀, 프레임워크",        "/ˈfreɪm.wɜːk/",     "noun",      3),
    ("function",     "기능",                 "/ˈfʌŋk.ʃən/",       "noun",      3),
    ("fund",         "자금",                 "/fʌnd/",            "noun",      3),
    ("fundamental",  "근본적인",             "/ˌfʌn.dəˈmen.təl/", "adjective", 3),
    ("furthermore",  "게다가",               "/ˌfɜː.ðəˈmɔːr/",     "adverb",    3),
    ("gender",       "성별",                 "/ˈdʒen.dər/",       "noun",      4),
    ("generate",     "생성하다",             "/ˈdʒen.ə.reɪt/",    "verb",      3),
    ("globe",        "지구, 구체",            "/ɡləʊb/",           "noun",      3),
    ("goal",         "목표",                 "/ɡəʊl/",            "noun",      3),
    ("grade",        "등급, 학년",            "/ɡreɪd/",           "noun",      3),
    ("grant",        "부여하다, 승인하다",     "/ɡrɑːnt/",          "verb",      3),
    ("guarantee",    "보장하다",             "/ˌɡær.ənˈtiː/",     "verb",      3),
    ("guideline",    "지침",                 "/ˈɡaɪd.laɪn/",      "noun",      3),
    ("hence",        "그러므로",             "/hens/",            "adverb",    3),
    ("hierarchy",    "계층",                 "/ˈhaɪə.rɑː.ki/",    "noun",      4),
    ("highlight",    "강조하다",             "/ˈhaɪ.laɪt/",       "verb",      3),
    ("hypothesis",   "가설",                 "/haɪˈpɒθ.ə.sɪs/",   "noun",      4),
    ("identical",    "동일한",               "/aɪˈden.tɪ.kəl/",   "adjective", 4),
    ("identify",     "식별하다, 확인하다",     "/aɪˈden.tɪ.faɪ/",   "verb",      3),
    ("ideology",     "이데올로기",           "/ˌaɪ.diˈɒl.ə.dʒi/", "noun",      4),
    ("ignorance",    "무지",                 "/ˈɪɡ.nər.əns/",     "noun",      4),
    ("illustrate",   "설명하다, 삽화를 넣다",  "/ˈɪl.ə.streɪt/",    "verb",      3),
]

WORDS_900 = [
    # TSL 900점 수준 (발음 기호 포함)
    ("abolish",      "폐지하다",             "/əˈbɒl.ɪʃ/",        "verb",      5),
    ("abrogate",     "폐기하다, 철폐하다",     "/ˈæb.rə.ɡeɪt/",     "verb",      5),
    ("abrupt",       "갑작스러운",           "/əˈbrʌpt/",         "adjective", 5),
    ("abstain",      "기권하다, 자제하다",     "/æbˈsteɪn/",        "verb",      5),
    ("abstract",     "추상적인; 개요",        "/ˈæb.strækt/",      "adjective", 5),
    ("abstruse",     "난해한",               "/æbˈstruːs/",       "adjective", 5),
    ("absurd",       "터무니없는",           "/əbˈsɜːd/",         "adjective", 5),
    ("abundant",     "풍부한",               "/əˈbʌn.dənt/",      "adjective", 5),
    ("abysmal",      "최악의, 심연의",        "/əˈbɪz.məl/",       "adjective", 5),
    ("accede",       "동의하다, 응하다",      "/əkˈsiːd/",         "verb",      5),
    ("accentuate",   "강조하다",             "/əkˈsen.tʃu.eɪt/",   "verb",      5),
    ("acclaim",      "환호하다, 칭송하다",     "/əˈkleɪm/",         "verb",      5),
    ("accolade",     "포상, 영예",           "/ˈæk.ə.leɪd/",      "noun",      5),
    ("accord",       "일치하다; 합의",        "/əˈkɔːd/",          "verb",      5),
    ("accrue",       "누적되다, 생기다",      "/əˈkruː/",          "verb",      5),
    ("acquiesce",    "묵인하다",             "/ˌæk.wiˈes/",       "verb",      5),
    ("acrimonious",  "험악한, 신랄한",        "/ˌæk.rɪˈməʊ.ni.əs/", "adjective", 5),
    ("acumen",       "통찰력, 안목",          "/ˈæk.ju.mən/",      "noun",      5),
    ("acute",        "심각한, 격렬한",        "/əˈkjuːt/",         "adjective", 5),
    ("adage",        "속담, 격언",           "/ˈæd.ɪdʒ/",         "noun",      5),
    ("adamant",      "단호한",               "/ˈæd.ə.mənt/",      "adjective", 5),
    ("adherent",     "지지자, 추종자",        "/ədˈhɪə.rənt/",     "noun",      5),
    ("adjourn",      "휴회하다, 연기하다",     "/əˈdʒɜːn/",         "verb",      5),
    ("admonish",     "꾸짖다, 충고하다",      "/ədˈmɒn.ɪʃ/",       "verb",      5),
    ("adroit",       "능숙한",               "/əˈdrɔɪt/",         "adjective", 5),
    ("adulation",    "과찬, 아첨",           "/ˌæd.jəˈleɪ.ʃən/",   "noun",      5),
    ("adulterate",   "불순물을 섞다",        "/əˈdʌl.tə.reɪt/",    "verb",      5),
    ("adversity",    "역경, 고난",           "/ədˈvɜː.sə.ti/",     "noun",      5),
    ("aesthetic",    "미적인",               "/esˈθet.ɪk/",       "adjective", 5),
    ("affable",      "상냥한",               "/ˈæf.ə.bəl/",       "adjective", 5),
    ("affinity",     "친밀감, 유사성",        "/əˈfɪn.ə.ti/",       "noun",      5),
    ("affluence",    "풍요, 부",             "/ˈæf.lu.əns/",      "noun",      5),
    ("aggrandize",   "확대하다, 강화하다",     "/əˈɡræn.daɪz/",     "verb",      5),
    ("aggregate",    "합계의; 집합",          "/ˈæɡ.rɪ.ɡət/",      "adjective", 5),
    ("agility",      "민첩함",               "/əˈdʒɪl.ə.ti/",      "noun",      5),
    ("alacrity",     "선뜻 ~함, 민활함",      "/əˈlæk.rə.ti/",      "noun",      5),
    ("alert",        "경계하는",             "/əˈlɜːt/",          "adjective", 5),
    ("alienate",     "멀어지게 하다",         "/ˈeɪ.li.ə.neɪt/",    "verb",      5),
    ("alleviate",    "완화하다",             "/əˈliː.vi.eɪt/",    "verb",      5),
    ("allocate",     "할당하다",             "/ˈæl.ə.keɪt/",      "verb",      5),
    ("altruism",     "이타주의",             "/ˈæl.tru.ɪ.zəm/",    "noun",      5),
    ("amalgamate",   "합병하다",             "/əˈmæl.ɡə.meɪt/",   "verb",      5),
    ("ambiguous",    "모호한",               "/æmˈbɪɡ.ju.əs/",    "adjective", 5),
    ("ambivalence",  "반대 감정 병존",        "/æmˈbɪv.ə.ləns/",   "noun",      5),
    ("ameliorate",   "개선하다",             "/əˈmiː.li.ə.reɪt/",  "verb",      5),
    ("amenable",     "순종하는",             "/əˈmiː.nə.bəl/",    "adjective", 5),
    ("amicable",     "우호적인",             "/ˈæm.ɪ.kə.bəl/",    "adjective", 5),
    ("amnesty",      "사면",                 "/ˈæm.nə.sti/",      "noun",      5),
    ("anachronism",  "시대착오",             "/əˈnæk.rə.nɪ.zəm/",  "noun",      5),
    ("analogous",    "유사한",               "/əˈnæl.ə.ɡəs/",     "adjective", 5),
    ("anarchy",      "무정부 상태",           "/ˈæn.ə.ki/",        "noun",      5),
    ("anathema",     "저주, 아주 싫은 것",    "/əˈnæθ.ə.mə/",      "noun",      5),
    ("ancillary",    "보조적인",             "/ænˈsɪl.ər.i/",     "adjective", 5),
    ("animosity",    "반감, 적대감",          "/ˌæn.ɪˈmɒs.ə.ti/",   "noun",      5),
    ("annihilate",   "전멸시키다",           "/əˈnaɪ.ə.leɪt/",    "verb",      5),
    ("annotate",     "주석을 달다",          "/ˈæn.ə.teɪt/",      "verb",      5),
    ("anomaly",      "이상, 변칙",           "/əˈnɒm.ə.li/",      "noun",      5),
    ("antagonism",   "적대감",               "/ænˈtæɡ.ə.nɪ.zəm/",  "noun",      5),
    ("antecedent",   "선행 사건",            "/ˌæn.tiˈsiː.dənt/",  "noun",      5),
    ("antipathy",    "반감",                 "/ænˈtɪp.ə.θi/",     "noun",      5),
    ("antiquity",    "고대",                 "/ænˈtɪk.wə.ti/",    "noun",      5),
    ("antithesis",   "정반대",               "/ænˈtɪθ.ə.sɪs/",    "noun",      5),
    ("apathy",       "무관심",               "/ˈæp.ə.θi/",        "noun",      5),
    ("apex",         "정점",                 "/ˈeɪ.peks/",        "noun",      5),
    ("aphorism",     "격언",                 "/ˈæf.ə.rɪ.zəm/",    "noun",      5),
    ("aplomb",       "침착함",               "/əˈplɒm/",          "noun",      5),
    ("apocryphal",   "출처가 의심스러운",      "/əˈpɒk.rɪ.fəl/",    "adjective", 5),
    ("appease",      "달래다",               "/əˈpiːz/",          "verb",      5),
    ("apposite",     "적절한",               "/ˈæp.ə.zɪt/",       "adjective", 5),
    ("apprehensive", "불안한",               "/ˌæp.rɪˈhen.sɪv/",  "adjective", 5),
    ("approbation",  "승인, 찬성",           "/ˌæp.rəˈbeɪ.ʃən/",   "noun",      5),
    ("arbitrary",    "독단적인",             "/ˈɑː.bɪ.trər.i/",   "adjective", 5),
    ("arcane",       "신비로운, 비밀의",      "/ɑːˈkeɪn/",         "adjective", 5),
    ("archaic",      "구식의, 고대의",        "/ɑːˈkeɪ.ɪk/",       "adjective", 5),
    ("archetype",    "원형",                 "/ˈɑː.kɪ.taɪp/",     "noun",      5),
    ("ardent",       "열렬한",               "/ˈɑː.dənt/",        "adjective", 5),
    ("arduous",      "힘든",                 "/ˈɑː.dʒu.əs/",      "adjective", 5),
    ("articulate",   "분명히 표현하다",       "/ɑːˈtɪk.jə.lət/",   "verb",      5),
    ("ascertain",    "확인하다",             "/ˌæs.əˈteɪn/",      "verb",      5),
    ("ascetic",      "금욕적인",             "/əˈset.ɪk/",       "adjective", 5),
    ("ascribe",      "~의 탓으로 돌리다",     "/əˈskraɪb/",        "verb",      5),
    ("aspersion",    "비방",                 "/əˈspɜː.ʒən/",      "noun",      5),
    ("assiduity",    "부지런함",             "/ˌæs.ɪˈdjuː.ə.ti/",  "noun",      5),
    ("assuage",      "완화하다, 달래다",      "/əˈsweɪdʒ/",        "verb",      5),
    ("astute",       "기민한, 영악한",        "/əˈstjuːt/",        "adjective", 5),
    ("atrophy",      "위축(증)",              "/ˈæt.rə.fi/",       "noun",      5),
    ("attenuate",    "약화시키다",           "/əˈten.ju.eɪt/",    "verb",      5),
    ("audacious",    "대담한",               "/ɔːˈdeɪ.ʃəs/",      "adjective", 5),
    ("augment",      "늘리다, 증가시키다",     "/ɔːɡˈment/",        "verb",      5),
    ("augury",       "전조",                 "/ˈɔː.ɡjə.ri/",       "noun",      5),
    ("auspicious",   "상서로운, 길조의",      "/ɔːˈspɪʃ.əs/",      "adjective", 5),
    ("austere",      "엄격한, 소박한",        "/ɔːˈstɪər/",         "adjective", 5),
    ("autocratic",   "독재적인",             "/ˌɔː.təˈkræt.ɪk/",   "adjective", 5),
    ("autonomy",     "자치, 자율",           "/ɔːˈtɒn.ə.mi/",      "noun",      5),
    ("avarice",      "침욕",                 "/ˈæv.ər.ɪs/",       "noun",      5),
    ("aver",         "단언하다",             "/əˈvɜːr/",          "verb",      5),
    ("aversion",     "혐오",                 "/əˈvɜː.ʒən/",       "noun",      5),
    ("avid",         "열광적인",             "/ˈæv.ɪd/",          "adjective", 5),
    ("avow",         "공언하다",             "/əˈvaʊ/",           "verb",      5),
    ("axiom",        "공리, 격언",           "/ˈæk.si.əm/",       "noun",      5),
]

SETS = [
    {
        "title": "토익 기초 필수 200",
        "description": "NGSL 상위 빈출 기초 어휘 200단어.",
        "level": "basic",
        "display_order": 1,
        "words": BASIC_WORDS,
    },
    {
        "title": "토익 800점 목표 어휘",
        "description": "TSL 기반 TOEIC 800점 목표 핵심 비즈니스 어휘.",
        "level": "800",
        "display_order": 2,
        "words": WORDS_800,
    },
    {
        "title": "토익 900점 목표 고급 어휘",
        "description": "TSL 고급 비즈니스/법률/금융 전문 어휘.",
        "level": "900",
        "display_order": 3,
        "words": WORDS_900,
    },
]

def get_sync_conn():
    return psycopg2.connect(
        host=settings.POSTGRES_HOST,
        port=settings.POSTGRES_PORT,
        dbname=settings.POSTGRES_DB,
        user=settings.POSTGRES_USER,
        password=settings.POSTGRES_PASSWORD,
    )

def upsert_words(cur, words):
    pos_map = {
        "noun": "NOUN", "verb": "VERB", "adjective": "ADJECTIVE",
        "adverb": "ADVERB", "preposition": "PREPOSITION", "conjunction": "CONJUNCTION"
    }
    rows = [
        (w[0], w[1], w[2], pos_map.get(w[3].lower(), "OTHER"), w[4], False)
        for w in words
    ]
    execute_values(
        cur,
        """
        INSERT INTO voca_words (word, meaning, phonetic, pos, difficulty, is_premium)
        VALUES %s
        ON CONFLICT (word) DO UPDATE
          SET meaning = EXCLUDED.meaning,
              phonetic = EXCLUDED.phonetic,
              pos = EXCLUDED.pos::pos_enum,
              difficulty = EXCLUDED.difficulty
        """,
        rows,
        template="(%s, %s, %s, %s::pos_enum, %s, %s)",
        page_size=500,
    )
    cur.execute("SELECT word, id FROM voca_words WHERE word = ANY(%s)", ([w[0] for w in words],))
    return {row[0]: row[1] for row in cur.fetchall()}

def upsert_set(cur, title, description, level, display_order):
    cur.execute(
        """
        INSERT INTO voca_sets (title, description, level, display_order, is_premium)
        VALUES (%s, %s, %s, %s, false)
        ON CONFLICT (title) DO UPDATE
          SET description = EXCLUDED.description, level = EXCLUDED.level, display_order = EXCLUDED.display_order
        RETURNING id
        """,
        (title, description, level, display_order),
    )
    return cur.fetchone()[0]

def upsert_mappings(cur, set_id, word_id_map, words):
    rows = [(set_id, word_id_map[w[0]], idx) for idx, w in enumerate(words, start=1) if w[0] in word_id_map]
    execute_values(
        cur,
        "INSERT INTO voca_set_mappings (set_id, word_id, position) VALUES %s ON CONFLICT (set_id, word_id) DO UPDATE SET position = EXCLUDED.position",
        rows,
        page_size=500,
    )

def main():
    conn = get_sync_conn()
    conn.autocommit = False
    cur = conn.cursor()
    try:
        for vset in SETS:
            words = vset["words"]
            word_id_map = upsert_words(cur, words)
            set_id = upsert_set(cur, vset["title"], vset["description"], vset["level"], vset["display_order"])
            upsert_mappings(cur, set_id, word_id_map, words)
            conn.commit()
        print("Success")
    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
        raise
    finally:
        cur.close()
        conn.close()

if __name__ == "__main__":
    main()
