"""add last_reviewed_at

Revision ID: a6b37694a223
Revises: fbf1c3871267
Create Date: 2026-03-07 13:54:46.636272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b37694a223'
down_revision: Union[str, None] = 'fbf1c3871267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_word_progress', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='마지막으로 학습한 시각 (UTC)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_word_progress', 'last_reviewed_at')
    # ### end Alembic commands ###
