"""initial_schema

Revision ID: fbf1c3871267
Revises: 
Create Date: 2026-03-07 11:34:39.131528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf1c3871267'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment="묶음 이름 (e.g. '토익 기초 필수 300')"),
    sa.Column('description', sa.Text(), nullable=True, comment='묶음 설명'),
    sa.Column('level', sa.String(length=20), nullable=True, comment='수준 태그 (basic / 800 / 900)'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='로비 카드 노출 순서'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='True면 유료 구독 전용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('voca_words',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False, comment="영단어 (e.g. 'allocate')"),
    sa.Column('meaning', sa.Text(), nullable=False, comment="한국어 뜻 (e.g. '할당하다, 배분하다')"),
    sa.Column('example_sentence', sa.Text(), nullable=True, comment='예문 (Phase 2 AI 생성)'),
    sa.Column('pos', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PREPOSITION', 'CONJUNCTION', 'OTHER', name='pos_enum', create_constraint=True), nullable=False, comment='품사'),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False, comment='난이도 1(쉬움) ~ 5(어려움)'),
    sa.Column('is_premium', sa.Boolean(), nullable=False, comment='True면 유료 콘텐츠 (Phase 2)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voca_words_word'), 'voca_words', ['word'], unique=True)
    op.create_table('user_word_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='앱 사용자 UUID (auth 테이블 FK 예정)'),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False, comment='어떤 세트에서 학습했는지 추적'),
    sa.Column('repetition', sa.Integer(), nullable=False, comment='연속 정답 횟수 (오답 시 0으로 리셋)'),
    sa.Column('interval', sa.Integer(), nullable=False, comment='다음 복습까지 일(day) 수'),
    sa.Column('easiness_factor', sa.Float(), nullable=False, comment='SM-2 난이도 계수 (min=1.3, init=2.5)'),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False, comment='다음 복습 예정 시각 (UTC)'),
    sa.Column('status', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'MASTERED', name='progress_status_enum', create_constraint=True), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False, comment='누적 복습 횟수'),
    sa.Column('correct_reviews', sa.Integer(), nullable=False, comment='누적 정답 횟수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['voca_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['voca_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', 'set_id', name='uq_user_word_set')
    )
    op.create_index('idx_user_next_review', 'user_word_progress', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_user_word_progress_user_id'), 'user_word_progress', ['user_id'], unique=False)
    op.create_table('voca_set_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['voca_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['voca_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'word_id', name='uq_set_word')
    )
    op.create_index('idx_set_word', 'voca_set_mappings', ['set_id', 'word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_set_word', table_name='voca_set_mappings')
    op.drop_table('voca_set_mappings')
    op.drop_index(op.f('ix_user_word_progress_user_id'), table_name='user_word_progress')
    op.drop_index('idx_user_next_review', table_name='user_word_progress')
    op.drop_table('user_word_progress')
    op.drop_index(op.f('ix_voca_words_word'), table_name='voca_words')
    op.drop_table('voca_words')
    op.drop_table('voca_sets')
    # ### end Alembic commands ###
